theme: jekyll-theme-cayman

# Site wide configuration

title: Pythonkurs
locale: de_AT
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Benedikt neuhold
  avatar: 
  bio: "Python Kurs f√ºr das Gymnasium Hartberg"
  email: benedikt.neuhold@gym-hartberg.ac.at
  # Do not include the @ symbol in your Twitter username
  twitter: benschi11
  linkedin: #username
  github: benschi11
